<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GodHandTrainer</RootNamespace>
    <AssemblyName>GodHandTrainer</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
    <Authors>AFreoN</Authors>
    <Company>AFreoN</Company>
    <Product>God Hand Trainer</Product>
    <Copyright>Copyright (c) AFreoN</Copyright>
    <Version>1.0.1</Version>
  </PropertyGroup>

</Project>
